### ISSUE TITLE
Wide vs UWide status bars (Suggestion)

### ISSUE THREAD

**Issue by Raddatoons** [NightFright2k19/doom_widehud#2]
I was wondering if it would be possible to shrink some of the ultrawide huds to fit regular widescreen resolutions (16:9)?  Some of the ultrawide statusbars seem like they'll look fine in normal widescreen (ex. `rekkr_uwide.wad`, `fistful_uwide.wad`), while others, specifically the ones that feature bezels on the edges (ex. `chex_uwide.wad`, `btsx1/2_uwide.wad`, and especially `neis_uwide.wad`), get cut off on the ends by the lack of screen space.

Maybe offering them as a widescreen/ultrawide pairs for different monitors could work?  It'd be a decent bit of editing for some of them, but I'd be willing to help out if needed.  The non-ultrawide statusbars can be used as reference, since those seem pretty set in stone as the general hud resolution at 16:9 (looking at you, `doom_wide.wad`).

Admittedly this is more for use in something like Crispy Doom or Woof, where the hud is at a set resolution relative to the rest of the game, rather than GZDoom, where UI scaling is more flexible, and the ultrawide huds can be used with 16:9 monitors by scaling the hud itself down.  But considering the recent expansion from being called `zdoom_wide` to the more general `doom_wide` as of update 2204, I feel like this could be an excellent addition in the long run for casual users with more common resolutions.

**Comment by NightFright2k19** [comment]
Luckily, the old versions of the statusbars with "normal" widescreen dimensions are not lost, as they are part of older releases. I might bring them back and put the ultrawide versions in a separate folder. Some of the bars might have to be recreated however since they only exist as ultrawide versions.

One of these days I'll take a look at it to see how extensive such an endeavor would be. Anyway, I guess this is possible and should hopefully be done eventually.
