### ISSUE TITLE
HUD glitchy

### ISSUE THREAD

**Issue by sebastian926** [NightFright2k19/doom_widehud#4]
![Screenshot_Doom_20230208_194907](https://user-images.githubusercontent.com/106453610/217669244-312e9f94-1038-411b-ba12-86fce1771829.png)

Tried Zdoom and LZDoom and its the same.

**Comment by NightFright2k19** [comment]
Both ports are using highly deprecated code which does not include support for these widescreen images. You would have to use ports like Crispy, Woof, PrBoom+ or GZDoom, I'm afraid. Nothing I can do here.

**Comment by sebastian926** [comment]
Oh ok, but i remember that i had one version which worked with ZDoom, but i lost it. Is one of the previous releases?

**Comment by NightFright2k19** [comment]
Older ports like ZDoom or LZDoom won't display these statusbars correctly since they do not support automatic centering of widescreen assets.

In such cases, you could manually apply offsets to the STBAR lump embedded within the wad files by using SLADE. You can find instructions regarding this process [here in the ZDoom forums](https://forum.zdoom.org/viewtopic.php?p=1182079#p1182079).

I will also add these instructions to the readme.
